import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import createSettingsObject from "@/utils/utils";
import {loadSettings} from "@/contentful/loadSettings";
import {SettingsProvider} from "@/contexts/SettingsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const settings = await loadSettings();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
       <SettingsProvider lang={"en"} settings={settings}>

       <Providers>{children}</Providers>
       </SettingsProvider>

      </body>
    </html>
  );
}
